name: new work
on:
  push:
    branches:
      -main
      -dev
jobs:
  first-job:
    runs-on: ubuntu-larest
    steps:
      -uses: actions/checkout@v2
      -name: first shell command
      run: echo "first shell command"
      shell: bash
  last-job:
    runs-on: ubuntu-larest
    steps:
      -name: second shell command
      run: echo "second shell command"
      shell: bash
